### ISSUE TITLE
Search api query - all issues for an organization matching a label

### ISSUE THREAD

**Issue by jywarren** [MichielvdVelde/github-api-simple#3]
This isn't in the standard API but the Search API -- https://api.github.com/search/issues?q=org%3Apubliclab+label%3Afirst-timers-only

is this something I could write a route for? Name it maybe `getIssuesForOrg`?

**Comment by MichielvdVelde** [comment]
The routes are based on placeholders (%s) filled in by the method's arguments, so if I understand your question correctly, it would be something like this (in `routes.json`:

```json
{
  "method": "getIssuesForOrg",
  "uri": "/search/issues/?q=org:%s+label:%s"
}
```

And use it like this:

```js
api.getIssuesForOrg('my-org', 'label')
```

I hope I understood your question correctly. If not, let me know, and I'll see if I can rectify the situation :)

**Comment by jywarren** [comment]
Yes, i think that works -- thanks, shall I open a PR? I was asking in part
also because all existing methods are part of the main GitHub API and this
would be the first to use the search API, so just checking that you're OK
with that. Thanks!

**Comment by MichielvdVelde** [comment]
I have no issue with it. As long as the endpoint doesn't require authentication, I think it's applicable to this project. You may want to add a namespace `Search` though. A PR would be more than welcome. After I've merged it I will release a new version.
